name: CI & Release

on:
  push:
    branches:
      - main

jobs:
  # ───────────────────────────────────────────────────────────────
  # Job A: Ruff lint / format checks (runs on every push)
  # ───────────────────────────────────────────────────────────────
  ruff:
    name: "Lint with Ruff"
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code (tous les tags et l’historique)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Installer Python et cacher pip
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      # 3) Cacher le dossier de cache de Ruff
      - name: Cache Ruff
        uses: actions/cache@v3
        with:
          path: .ruff_cache
          key: ${{ runner.os }}-ruff-${{ hashFiles('**/*.py') }}

      # 4) Installer les dépendances Python
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Lint complet (parallélisé)
      - name: Run Ruff lint (all files)
        run: python -m ruff check . --jobs 4

      # 6) Vérification du format Ruff
      - name: Run Ruff format check
        run: python -m ruff format . --check --jobs 4

  # ───────────────────────────────────────────────────────────────
  # Job B: Detect manifest.json changes (after ruff)
  # ───────────────────────────────────────────────────────────────
  filter_manifest:
    name: "Detect manifest.json changes"
    runs-on: ubuntu-latest
    needs: ruff
    outputs:
      manifest: ${{ steps.manifest_filter.outputs.manifest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: manifest_filter
        name: Filter for manifest.json
        uses: dorny/paths-filter@v2
        with:
          filters: |
            manifest:
              - 'custom_components/ha_anniversaries_export_ics/manifest.json'

  # ───────────────────────────────────────────────────────────────
  # Job C: Release (only if manifest.json changed & lint passed)
  # ───────────────────────────────────────────────────────────────
  release:
    name: "Release on version bump"
    runs-on: ubuntu-latest
    needs:
      - ruff
      - filter_manifest
    # N'exécute ce job que si manifest.json a changé
    if: needs.filter_manifest.outputs.manifest == 'true'
    permissions:
      contents: write

    steps:
      # 1) Checkout code (nécessaire pour tag & zip)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) (Optionnel) Mettre en cache pip ici si tu lis la version en Python
      - name: Set up Python (to parse manifest)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      # 3) Extraire la version brute depuis manifest.json (sans jq)
      - name: Get version from manifest.json
        id: get_version
        run: |
          python3 - <<EOF >version.txt
import json
mf = json.load(open('custom_components/ha_anniversaries_export_ics/manifest.json'))
print(mf['version'])
EOF
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 4) Vérifier si le tag existe
      - name: Check for existing Git tag
        id: check_tag
        run: |
          TAG=${{ steps.get_version.outputs.version }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 5) Créer & pousser le tag si besoin
      - name: Create & push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          TAG=${{ steps.get_version.outputs.version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"

      # 6) Archiver l’intégration
      - name: Package integration
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          cd custom_components/ha_anniversaries_export_ics
          zip -r ha_anniversaries_export_ics.zip ./

      # 7) Créer et uploader la Release
      - name: Create GitHub Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: ${{ contains( steps.get_version.outputs.version, '-' ) || contains( steps.get_version.outputs.version, 'b') || contains( steps.get_version.outputs.version, 'rc') }}
          files: custom_components/ha_anniversaries_export_ics/ha_anniversaries_export_ics.zip
